version: "2.0"
services:
  app:
    container_name: perfanalytics_app
    restart: always
    command: npm run start
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: perfanalytics_mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "database:/data/database"

volumes:
  database: