#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
    
      - run: npm install

      - run: npm install --prefix dashboard

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!

      - run: npm run build --prefix dashboard

      - run: npm run build

  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Install Heroku CLI"
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Deploy Heroku Docker Container
          command: |
            heroku container:push --app $HEROKU_APP_NAME web
            heroku container:release --app $HEROKU_APP_NAME web

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master